### ISSUE TITLE
Red error thrown when starting a new colony

### ISSUE THREAD

**Issue by mk-over** [Dubwise56/Dubs-Mint-Minimap#3]
Hi @Dubwise56, thank you very much for your mods. I'm a personal fan of each one of them.

Lately I've been getting a red error when I start in a new map and leave the minimap as Rimatomics TACS only.

```
Root level exception in Update(): System.NullReferenceException: Object reference not set to an instance of an object
  at DubsMintMinimap.Harmony_RegenerateLayers.Postfix (Verse.Section __instance, Verse.MapMeshFlag changeType) [0x0004e] in <78e68cfc491d4219a906973b2ac48bfc>:0 
  at (wrapper dynamic-method) Verse.Section.DMD<DMD<RegenerateLayers_Patch1>?1460052096::RegenerateLayers_Patch1>(Verse.Section,Verse.MapMeshFlag)
  at Verse.MapDrawer.TryUpdateSection (Verse.Section sect) [0x00024] in <bbc76d4d64944976acb84ce2ce5457b4>:0 
  at Verse.MapDrawer.MapMeshDrawerUpdate_First () [0x00034] in <bbc76d4d64944976acb84ce2ce5457b4>:0 
  at Verse.Map.MapUpdate () [0x00086] in <bbc76d4d64944976acb84ce2ce5457b4>:0 
  at Verse.Game.UpdatePlay () [0x00031] in <bbc76d4d64944976acb84ce2ce5457b4>:0 
  at Verse.Root_Play.Update () [0x00026] in <bbc76d4d64944976acb84ce2ce5457b4>:0 
Verse.Log:Error(String, Boolean)
Verse.Root_Play:Update()
```
Here's a full Hugs log:
https://gist.github.com/7490b3907e9033b67dacc5047b1732fb

The error doesn't appear if the minimap is set to "free". Nothing else looks broken, just the one error. I use too many mods and I guess Real Fog of War or something else might be interfering with it. I didn't try messing with the load order to see how it behaves.

Don't know if this can help but I hope it does.
Keep up the awesome work!

**Comment by mk-over** [comment]
I can confirm this bug persists in version v1.3.447.

**Comment by Dubwise56** [comment]
tricky one, the tacs option works fine for me, there's nothing in that postfix that could be null in .447 since its all got null checks, its working for other people with heavily modded games, so going to be hard to work out what your specific issue is

**Comment by Dubwise56** [comment]
ok another update, maybe its fixed this time... i missed something simple

**Comment by mk-over** [comment]
Hi @Dubwise56, it seems the latest update (v1.3.448) did indeed fix it. Thanks a lot!

**Comment by mk-over** [comment]
I was wrong. The issue is still there. I understand it's complicated without finding a culprit so please allow me some time to try and find the conflicting mod.

**Comment by Dubwise56** [comment]
i just got this error for the first time while working on something else, so its probably an issue with timing and my map just loads very fast, i'll see if i can figure it out

**Comment by mk-over** [comment]
My maps loads very slow.
I noticed something about when I closed this issue: when I first loaded a modlist and started a new game, the issue didn't appear. If I quit the save, got back to the main menu and made a new game, the issue appears. It appears with any settings, not only with the minimap set to TACS only.

I'm still looking for potential conflicts.

**Comment by mk-over** [comment]
Alright, so testing started. I can confirm that it's more than one mod conflicting. From that huge list, I can confirm Save our Ship 2 to be one of them.

https://gist.github.com/4632e81018cecd5b645ded04a6c0f946

SoS2 error does not happen in the first map start, to reproduce it you need to follow the above's comment instruction.

**Comment by mk-over** [comment]
After further testing I can confirm that Real Fog of War is another culprit.

https://gist.github.com/HugsLibRecordKeeper/f72640452fe656348c063453f9e77654

There seems to be at least one more.

**Comment by mk-over** [comment]
The last error is hard to pinpoint to a specific mod. I reduced the list to a few, but I cannot have confirmation because in order to reproduce the bug I need to generate new worlds and maps all the time. It's not always the second colony you start, there's no telling when it will happen. 

Here's the log:
https://gist.github.com/a1c48e7f5b53554042f80ef950171566

Here's hoping any of this can be helpful to you @Dubwise56

**Comment by mk-over** [comment]
It seems the latest updated fixed all these issues, @Dubwise56. I tried multiple times and didn't see it pop up once. If I see them again, I will post here. Thanks again!
